name: Verify private docs access

on:
  workflow_dispatch: {}

jobs:
  verify-docs:
    runs-on: ubuntu-latest

    # https://github.com/actions/checkout?tab=readme-ov-file#recommended-permissions
    permissions:
      contents: read

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run access test (grep for 'WSL')
        run: |
          set -euo pipefail
          head -n 3 docs/troubleshoot/vscode/Invalid\ WSL\ distribution.md | grep WSL
