name: Verify private docs access

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  verify-docs:
    runs-on: ubuntu-latest

    # https://github.com/actions/checkout?tab=readme-ov-file#recommended-permissions
    # Fetching submodules requires write access to the repository contents
    permissions:
      contents: write

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.DOCS_GITHUB_PAT }}
          submodules: true

      - name: Run access test (grep for 'WSL')
        run: |
          set -euo pipefail
          head -n 3 docs/troubleshoot/vscode/Invalid\ WSL\ distribution.md | grep WSL
